services:
  hockey_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hockey_bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: always