services:
  hockey_bot:
    build: .
    container_name: hockey_bot
    env_file:
      - .env
    volumes:
      - ./data/database.db:/app/database.db
    restart: unless-stopped

volumes:
  hockey_bot_db: